"use client"
import { Disclosure, DisclosureButton, DisclosurePanel } from "@headlessui/react";
import { BiMinus, BiPlus } from "react-icons/bi";
import { motion } from "framer-motion";
import { FiDollarSign, FiCheckCircle, FiCalendar, FiPause, FiUsers, FiTrendingUp, FiHelpCircle, FiCpu } from "react-icons/fi";

const FAQ = () => {
  const faqs = [
    // {
    //   question: "How does Namaio trade for my account?",
    //   answer:
    //     "Namaio connects securely to your exchange account through API keys (you keep full control of your funds). The software automatically executes buy and sell orders based on its strategy, while you can track all trades in real time from your dashboard. Your money never leaves your exchange, Namaio only places trades on your behalf.",
    //   icon: FiCpu, // you can pick a better icon, e.g., FiSettings or FiCpu
    // },
    // {
    //   question: "Do all members see the same results?",
    //   answer:
    //     "No. All members get the same trading signals, but results are not always identical. The amount you invest, the fees charged by your exchange, and the speed of trade execution can lead to differences in results.",
    //   icon: FiUsers,
    // },

    // {
    //   question: "When do I start seeing results?",
    //   answer: "Same day you connect",
    //   icon: FiDollarSign
    // },
    // {
    //   question: "Can I stop anytime?",
    //   answer: "Yes, you can stop at any time. There are no commitments or lock-ins.",
    //   icon: FiDollarSign,
    // },
    // {
    //   question: "Do I control my funds?",
    //   answer: "Yes, 100% of your funds always remain in your own exchange account.",
    //   icon: FiDollarSign,
    // },

    {
      question: "How does the 15% profit share work?",
      answer: (
        <>
          We calculate net realized profit for the billing period that's all winning trades minus all losing trades, after exchange trading fees, excluding deposits and withdrawals.
          <br /><br />
          If net profit is positive, we invoice 15% of that amount. If it's zero or negative, you pay nothing for that month beyond your subscription fee.
        </>
      ),
      icon: FiDollarSign
    },
    {
      question: "Do I still pay profit share if I trade manually?",
      answer: (
        <>
          No. Profit share applies only to profits generated by Namaio's auto execution.
          <br /><br />
          If you're on a signals only plan and do all execution manually, you only pay the monthly subscription.
        </>
      ),
      icon: FiCheckCircle
    },
    {
      question: "When do I get billed for profit share?",
      answer: (
        <>
          Profit share is billed monthly on the 1st of each month for the previous month's trading results.
          <br /><br />
          You'll receive a detailed report showing:
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Your monthly net profit</li>
            <li>The 15% calculation</li>
            <li>The final amount due (if any)</li>
          </ul>
        </>
      ),
      icon: FiCalendar
    },
    {
      question: "What happens if I don't pay my profit share invoice?",
      answer: (
        <>
          We allow a 7 day grace period.
          <br /><br />
          After that, your bot access will be paused until payment is received.
          <br /><br />
          You'll still have full access to your dashboard and past trade history.
        </>
      ),
      icon: FiPause
    },
    {
      question: "How do affiliates get paid?",
      answer: (
        <>
          Affiliate commissions come from our 15% profit share, so your referred traders never pay extra.
          <br /><br />
          Affiliate earnings are also visible in real time on their personal dashboard.
        </>
      ),
      icon: FiUsers
    },
    {
      question: "What if I have no profitable trades in a month?",
      answer: "You'll pay $0 profit share for that month, just your monthly subscription fee.",
      icon: FiCheckCircle
    },
    {
      question: "Can I see how my profit share is calculated?",
      answer: (
        <>
          Yes. Your dashboard shows:
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Daily PnL</li>
            <li>Monthly cumulative PnL</li>
            <li>Exact 15% profit share calculation</li>
          </ul>
        </>
      ),
      icon: FiTrendingUp
    }
  ];

  return (
    <section id="profitsharing" className="py-24 px-4 sm:px-6 lg:px-8 bg-gray-900 text-white">

      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-10"
        >
          <div className="flex items-center justify-center mb-10">
            <div className="inline-flex items-center gap-3 bg-gray-800 px-6 py-3 rounded-full">
              <FiHelpCircle className="w-6 h-6 text-blue-400" /> {/* Added explicit size */}
              <h2 className="text-2xl font-bold text-white">  Profit Sharing FAQ</h2> {/* Adjusted text size */}
            </div>
          </div>
          {/* <div className="inline-flex items-center gap-3 bg-gray-800 px-6 py-3 rounded-full mb-6 mx-auto">
            <FiHelpCircle className="w-5 h-5 text-blue-400" />
            <span className="text-blue-400 font-bold">PROFIT SHARE & BILLING</span>
          </div> */}

          {/* <h2 className="text-5xl lg:text-6xl font-bold mb-6">
            <span className="text-white">Profit Sharing FAQ</span>
          </h2> */}

          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Clear answers about our 15% profit sharing model and billing process.
          </p>
        </motion.div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <Disclosure key={index} as="div" className="bg-gray-800/50 rounded-xl border border-gray-700 ">
              {({ open }) => (
                <>
                  <DisclosureButton className="flex justify-between items-center w-full px-6 py-5 text-left hover:bg-gray-700/30 transition-colors">
                    <div className="flex items-center gap-4">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${open ? 'bg-blue-600' : 'bg-gray-700'}`}>
                        {/* <faq.icon className="w-5 h-5 text-white" /> */}
                        <h2 className="text-white">{index + 1}</h2>
                      </div>
                      <span className="text-lg font-semibold text-white">{faq.question}</span>
                    </div>
                    {open ? (
                      <BiMinus className="w-6 h-6 text-blue-400" />
                    ) : (
                      <BiPlus className="w-6 h-6 text-blue-400" />
                    )}
                  </DisclosureButton>
                  <DisclosurePanel className="px-6 pb-5">
                    <div className="pl-14 text-gray-300">
                      {faq.answer}
                    </div>
                  </DisclosurePanel>
                </>
              )}
            </Disclosure>
          ))}
        </div>
      </div>

    </section>
  );
};

export default FAQ;