'use client'
import { motion } from 'framer-motion'

export default function TermsAndConditions() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <h1 className="text-3xl font-bold text-center mb-2 text-white">
          Tezcai Terms of Service
        </h1>
        {/* <p className="text-gray-500 text-center mb-12">Last updated: [DATE]</p> */}

        <div className="prose prose-invert max-w-none">
          <p className="mb-6">
            These Terms of Service ("Terms") govern your access to and use of Tezcai ("Tezcai," "we," "us," "our") software and services, including our website, apps, dashboards, trading automation, and smart trading signals (collectively, the "Services"). By creating an account or using the Services, you agree to these Terms.
          </p>
          <p className="mb-6 font-medium">
            Important fees: Tezcai charges (i) a monthly subscription and (ii) a performance based profit share of 15% on net realized profits generated by Tezcai auto execution (where enabled). Details are below.
            If you do not agree, do not use the Services.
          </p>

          <h2 className="text-xl font-semibold mb-4">1) Definitions</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li><strong>Account:</strong> Your Tezcai account and connected exchange accounts.</li>
            <li><strong>Auto Execution:</strong> Tezcai placing orders automatically on your connected exchange via API.</li>
            <li><strong>Signals Only:</strong> Tezcai provides trade signals; you place orders manually.</li>
            <li><strong>Billing Period:</strong> Calendar month (00:00 on the 1st to 23:59:59 last day, your local time unless otherwise stated).</li>
            <li><strong>Net Realized Profit:</strong> Sum of realized gains minus realized losses for the Billing Period after exchange fees, excluding deposits/withdrawals and unrelated/manual trades.</li>
            <li><strong>Profit Share:</strong> 15% of Net Realized Profit generated by Tezcai Auto Execution (if enabled for your plan).</li>
            <li><strong>Exchange:</strong> Third party platform (e.g., Binance) where your funds are held and trades are executed.</li>
            <li><strong>User Content:</strong> Data you provide (API keys, settings, preferences, etc.).</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">2) Plans & Pricing</h2>
          <p className="mb-4">We currently offer:</p>
          <h3 className="font-medium mb-2">a) Signal — $9.99/month</h3>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Smart Filtered Trade Signals.</li>
            <li>Momentum Identification.</li>
            <li>Trend Confirmation.</li>
            {/* <li>Volume Analysis.</li> */}

          </ul>
          {/* <h3 className="font-medium mb-2">b) Starter — $19.99/month</h3>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Smart bot executes trades automatically on your exchange wallet.</li>
            <li>Two trades executed daily, selects only high probability setups.</li>
            <li>Live performance dashboard (PnL, win rate, trade log).</li>
          </ul> */}
          <h3 className="font-medium mb-2">b) Pro — $29.99/month</h3>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Unlimited High-Probability Trades.</li>
            <li>Priority Support (4 Hour Response).</li>
            <li>Live Chat Support.</li>
             <li>Weekly Pro Insights Report</li>
          </ul>
          <h3 className="font-medium mb-2">c) Enterprise — Custom</h3>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>White label, custom strategies, API/webhooks, bulk onboarding, dedicated manager, priority execution, custom reporting, training.</li>
            <li>If Auto Execution is enabled, Profit Share applies (15% of monthly Net Realized Profit).</li>
          </ul>
          <p className="mb-6">
            Taxes: All fees are exclusive of taxes (e.g., VAT). Applicable taxes may be added to your invoice.
          </p>

          <h2 className="text-xl font-semibold mb-4">3) Profit Share — Calculation & Billing</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>What is charged: 15% of Net Realized Profit generated by Auto Execution within the Billing Period.</li>
            <li>Only on winning months: If Net Realized Profit ≤ 0 for the month, no Profit Share is charged.</li>
            <li>Signals Only: No Profit Share applies to purely manual trading (Pro default), unless you activate Auto Execution.</li>
            <li>When billed: Invoices issued on the 1st of each month for the prior month.</li>
            <li>Grace period: 7 days from invoice date to pay. After the grace period, we may pause your bot access.</li>
            <li>Transparency: Your dashboard shows daily PnL, monthly Net Realized Profit, and the exact Profit Share calculation.</li>
            <li>Disputes: You must dispute an invoice within 5 business days of issue; include trade IDs and details. We'll review in good faith.</li>
          </ul>
          <p className="mb-4">Examples</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Net Realized Profit = $1,000 → Profit Share = $150.</li>
            <li>Net Realized Profit = $0 or negative → Profit Share = $0.</li>
          </ul>
          <p className="mb-6">
            Affiliates: Commissions are paid from our 15%; your fees don't increase when using a referral link.
          </p>

          <h2 className="text-xl font-semibold mb-4">4) Subscriptions, Renewals, Refunds, Cancellation</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Billing cycle: Monthly, starting on your activation date. Auto renews unless canceled.</li>
            <li>Refunds: Subscriptions are non refundable once a cycle begins. Cancel anytime to stop the next cycle.</li>
            <li>Cancellation: You may cancel in the app/dashboard. Auto Execution stops upon cancellation or suspension.</li>
            <li>Non payment: Unpaid invoices after the grace period may result in suspension until payment.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">5) No Custody; Your Responsibilities</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>No custody: We do not hold your funds. Your assets remain on your exchange wallet.</li>
            <li>API permissions: You must configure read + trade (spot/margin as applicable) and disable withdrawals. Use IP whitelisting if available.</li>
            <li>Accuracy: You are responsible for correct API setup, balances, margin settings, and keeping keys confidential.</li>
            <li>Compliance: You are responsible for complying with your local laws/taxes and your Exchange's terms.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">6) Trading & Risk Disclosure</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>High risk: Crypto trading is volatile and may result in partial or total loss.</li>
            <li>No guarantee: Past performance (e.g., ~75% win rate; ~1.5% per winning trade) does not guarantee future results.</li>
            <li>Slippage/latency: Market conditions may result in slippage, partial fills, or delayed execution.</li>
            <li>Exchange dependency: Downtime, API limits, or rule changes at your Exchange can affect performance or availability.</li>
            <li>Your capital: Only trade with funds you can afford to lose.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">7) Availability & Support</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Uptime: We aim for high availability but provide no absolute uptime guarantee.</li>
            <li>Maintenance: We may conduct maintenance with or without notice.</li>
            <li>Support: Email or in app support during business hours [YOUR TIME ZONE]. Priority support for Pro/Enterprise.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">8) Acceptable Use</h2>
          <p className="mb-4">You agree not to:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Use the Services for unlawful purposes, market manipulation, or sanctions evasion.</li>
            <li>Interfere with or overload our systems (e.g., scraping, brute force).</li>
            <li>Share, resell, or sublicense your account without permission.</li>
            <li>Attempt to reverse engineer or copy our models/algorithms.</li>
          </ul>
          <p className="mb-6">We may suspend or terminate for violations.</p>

          <h2 className="text-xl font-semibold mb-4">9) Data, Privacy & Security</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Data processing: We process your data (e.g., API keys, settings, trades) to provide the Services.</li>
            <li>Security: We use encryption at rest and in transit for API keys and sensitive data.</li>
            <li>Privacy Policy: Our Privacy Policy (incorporated by reference) explains how we collect, use, and protect your data.</li>
            <li>Anonymized analytics: We may use aggregated/anonymized data to improve Services.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">10) Intellectual Property & License</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Our IP: The Services, software, AI models, branding, and content are protected and owned by Tezcai.</li>
            <li>Your license: We grant you a limited, revocable, non exclusive, non transferable license to use the Services for your personal or internal business trading.</li>
            <li>Feedback: You grant us a royalty free right to use feedback to improve the Services.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">11) Third Party Services & Exchanges</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>We are not responsible for third party services (Exchanges, data providers, wallets).</li>
            <li>Your relationship with an Exchange is governed by that Exchange's terms.</li>
            <li>We cannot control Exchange downtime, API changes, or fees.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">12) Taxes</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>You are responsible for any tax liabilities arising from trading profits (including income or capital gains).</li>
            <li>Fees we charge may be subject to indirect taxes (e.g., VAT) per applicable law.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">13) Restricted & Prohibited Use</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>You may not use the Services if you are in a sanctioned jurisdiction or otherwise restricted under applicable laws.</li>
            <li>We may request KYC/AML information if required by law or our partners. Failure to provide may result in suspension.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">14) Changes to the Services or Terms</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>We may modify the Services or these Terms at any time.</li>
            <li>Material changes will be notified via email or in app. Continued use after changes means acceptance.</li>
            <li>If you do not agree, stop using the Services and cancel your subscription.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">15) Termination</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>By you: Cancel anytime (effective end of billing cycle).</li>
            <li>By us: We may suspend/terminate for breach, non payment, or legal/compliance reasons.</li>
            <li>Effect: Upon termination, Auto Execution stops; you retain dashboard access to historical data for a reasonable period.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">16) Disclaimers; Limitation of Liability</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>"As is" basis: Services are provided as is and as available without warranties of any kind.</li>
            <li>No financial advice: Tezcai provides tools/signals; we do not provide investment, legal, or tax advice.</li>
            <li>Liability cap: To the maximum extent permitted by law, Tezcai's aggregate liability for claims relating to the Services is limited to the fees you paid to Tezcai in the 3 months preceding the event giving rise to the claim.</li>
            <li>No indirect damages: We are not liable for lost profits, loss of data, or indirect, incidental, or consequential damages.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">17) Indemnity</h2>
          <p className="mb-6">
            You agree to indemnify and hold Tezcai harmless from claims, damages, liabilities, and expenses (including reasonable legal fees) arising from your misuse of the Services, violation of these Terms, or breach of law.
          </p>

          <h2 className="text-xl font-semibold mb-4">18) Governing Law; Dispute Resolution</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Governing law: These Terms are governed by the laws of the United Arab Emirates.</li>
            <li>Venue: Courts of Abu Dhabi, UAE shall have exclusive jurisdiction.</li>
            <li>Alternative: For Enterprise customers, the parties may agree to arbitration under ADGM Arbitration Regulations in Abu Dhabi.</li>
          </ul>

          <h2 className="text-xl font-semibold mb-4">19) Electronic Communications & E Signature</h2>
          <p className="mb-6">
            You consent to receive notices electronically and agree that ticking checkboxes, clicking "I Agree," or similar actions constitute your electronic signature.
          </p>
        </div>
        <div className="flex justify-center">
          <button
            onClick={() => window.history.back()}
            className="px-6 py-3 bg-gray-700 text-white rounded-lg hover:bg-gray-600 transition-colors"
          >
            Go Back
          </button>
        </div>
      </motion.div>
    </div>
  )
}